- hosts: all
  connection: local
  tasks:
    - include_role:
        name: turbo-test-suite
      vars: 
        description: >
          Run test suite on endpoint in order to ensure the target system/platform
          that hosts your application is in good health. if the test suite 
          does not pass stop and log error. Will block until a 
          {"result": true} or {"result": false} is returned. false => stop, true => continue

    - include_role:
        name: ansible-role-rhel7-stig
      vars: 
        description: >
          Run vulnerabilty fix for target platform on endpoint. Will apply
          any selected vulnerability mitigations. Log errors, or any fixes that must be manual.
        apply:
          become: yes
          tags:
            - CCE-27351-6

    - include_role:
        name: turbo-test-suite
      vars: 
        description: >
          Ensure that nothing was broken on the endpoint that had STIGS applied.
          Run test suite on endpoint in order to ensure the target system/platform
          that hosts your application is in good health. if the test suite 
          does not pass stop and log error. Will block until a 
          {"result": true} or {"result": false} is returned. false => stop, true => continue


