# Generated by Django 3.1.1 on 2020-09-13 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('checklist_name', models.CharField(max_length=36, unique=True)),
                ('checklist_id', models.AutoField(primary_key=True, serialize=False)),
                ('json_config', models.TextField(max_length=1000)),
                ('stig', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VulnRemove',
            fields=[
                ('remove_id', models.AutoField(primary_key=True, serialize=False)),
                ('fix_id', models.CharField(max_length=36, unique=True)),
                ('remove_url', models.CharField(max_length=36, unique=True)),
                ('remove_status', models.CharField(max_length=36)),
                ('last_run_time', models.CharField(max_length=36)),
                ('checklist_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.checklist')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='VulnFix',
            fields=[
                ('fix_id', models.AutoField(primary_key=True, serialize=False)),
                ('fix_name', models.CharField(max_length=36, unique=True)),
                ('fix_url', models.CharField(max_length=36, unique=True)),
                ('removal_id', models.CharField(max_length=36)),
                ('fix_status', models.CharField(max_length=36)),
                ('last_run_time', models.CharField(max_length=36)),
                ('checklist_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.checklist')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('suite_id', models.AutoField(primary_key=True, serialize=False)),
                ('suite_url', models.URLField(unique=True)),
                ('last_run_time', models.CharField(max_length=36)),
                ('suite_status', models.CharField(max_length=36)),
                ('checklist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.checklist')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='Stig',
            fields=[
                ('stig_id', models.AutoField(primary_key=True, serialize=False)),
                ('stig_name', models.CharField(max_length=36, unique=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=36, unique=True)),
                ('last_run_time', models.CharField(max_length=36)),
                ('suite_test', models.CharField(max_length=36)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='CheckListItem',
            fields=[
                ('checklist_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('checklist_item_name', models.CharField(max_length=36, unique=True)),
                ('vuln_id', models.CharField(max_length=36)),
                ('fix_id', models.CharField(max_length=36, unique=True)),
                ('removal_id', models.CharField(max_length=36, unique=True)),
                ('vuln_text', models.TextField(max_length=1500)),
                ('vuln_sev', models.CharField(max_length=36)),
                ('vuln_discussion', models.TextField(max_length=1500)),
                ('vuln_check_content', models.TextField(max_length=1500)),
                ('vuln_finding_details', models.TextField(max_length=1500)),
                ('vuln_reference', models.TextField(max_length=1500)),
                ('vuln_status', models.CharField(max_length=36)),
                ('vuln_comments', models.TextField(max_length=1500)),
                ('checklist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.checklist')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
        ),
        migrations.AddField(
            model_name='checklist',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project'),
        ),
    ]
